<?php
$m67="m251.gif";
$m68="m252.gif";
$m69="m253.gif";
$m70="m262.gif";
$m71="m261.gif";
$m72="m271.gif";
$m73="m272.gif";
$m74="m273.gif";
$m75="m281.gif";
$m76="m282.gif";
$m77="m283.gif";
$m78="m291.gif";
$m79="m292.gif";
$m80="m293.gif";
$m81="m301.gif";
$m82="m302.gif";
$m83="m303.gif";
$m84="m311.gif";
$m85="m312.gif";
$m86="m313.gif";
$m87="m321.gif";
$m88="m322.gif";
$m89="m323.gif";
$m90="m332.gif";
$m91="m331.gif";
$m92="m341.gif";
$m93="m342.gif";
$m94="m343.gif";
$m95="m351.gif";
$m96="m353.gif";
$m97="m354.gif";
$m98="m361.gif";
$m99="m362.gif";
$p67="<A href='067-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m67."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p68="<A href='068-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m68."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p69="<A href='069-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m69."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p70="<A href='070-pohlednice-lednice.php'><img src='pm/".$m70."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE' title='LEDNICE'></a>";
$p71="<A href='071-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m71."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p72="<A href='072-pohlednice-lednice-januv-hrad.php'><img src='pm/".$m72."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednice - Janùv hrad' title='Lednice - Janùv hrad'></a>";
$p73="<A href='073-pohlednice-lednice-breclav-a-okoli.php'><img src='pm/".$m73."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednice, Bøeclav a okolí' title='Lednice, Bøeclav a okolí'></a>";
$p74="<A href='074-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m74."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednicko-valtický areál' title='Lednicko-valtický areál'></a>";
$p75="<A href='075-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m75."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p76="<A href='076-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m76."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p77="<A href='077-pohlednice-zamek-lednice.php'><img src='pm/".$m77."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Zámek LEDNICE' title='Zámek LEDNICE'></a>";
$p78="<A href='078-pohlednice-zamek-lednice.php'><img src='pm/".$m78."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Zámek LEDNICE' title='Zámek LEDNICE'></a>";
$p79="<A href='079-pohlednice-lednice-valtice.php'><img src='pm/".$m79."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE - VALTICE' title='LEDNICE - VALTICE'></a>";
$p80="<A href='080-pohlednice-podivin-mestanska-skola.php'><img src='pm/".$m80."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Mìšanská škola' title='Podivín - Mìšanská škola'></a>";
$p81="<A href='081-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m81."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - celkový pohled' title='Pozdrav z Podivína - celkový pohled'></a>";
$p82="<A href='082-pohlednice-pozdrav-z-podivina-nova-ulice.php'><img src='pm/".$m82."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Nová ulice' title='Pozdrav z Podivína - Nová ulice'></a>";
$p83="<A href='083-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m83."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel' title='Gruss aus Kostel'></a>";
$p84="<A href='084-pohlednice-podivin-skola-a-namesti.php'><img src='pm/".$m84."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. - Škola a námìstí' title='PODIVÍN. - Škola a námìstí'></a>";
$p85="<A href='085-pohlednice-podivin-tovarna.php'><img src='pm/".$m85."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. - Továrna' title='PODIVÍN. - Továrna'></a>";
$p86="<A href='086-pohlednice-januv-hrad.php'><img src='pm/".$m86."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='JANÙV HRAD' title='JANÙV HRAD'></a>";
$p87="<A href='087-pohlednice-janohrad.php'><img src='pm/".$m87."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='JANOHRAD' title='JANOHRAD'></a>";
$p88="<A href='088-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m88."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p89="<A href='089-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m89."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p90="<A href='090-pohlednice-zamecky-areal-lednice-valtice.php'><img src='pm/".$m90."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='ZÁMECKÝ AREÁL LEDNICE - VALTICE ' title='ZÁMECKÝ AREÁL LEDNICE - VALTICE '></a>";
$p91="<A href='091-pohlednice-podivin-janodrad-most-u-janohradu.php'><img src='pm/".$m91."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - JANODRAD Most u Janohradu: ' title='PODIVÍN - JANODRAD Most u Janohradu: '></a>";
$p92="<A href='092-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m92."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p93="<A href='093-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m93."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p94="<A href='094-pohlednice-gruss-aus-kostel-garten-aussicht-bahnol-bahnstasse.php'><img src='pm/".$m94."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel Garten Aussicht, Bahnof, Bahnstrasse ' title='Gruss aus Kostel Garten Aussicht, Bahnof, Bahnstrasse '></a>";
$p95="<A href='095-pohlednice-pozdrav-z-podivina-gruss-aus-kostel.php'><img src='pm/".$m95."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Gruß aus Kostel' title='Pozdrav z Podivína Gruß aus Kostel'></a>";
$p96="<A href='096-pohlednice-pozdrav-z-podivinacelkovy-pohled.php'><img src='pm/".$m96."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled' title='Pozdrav z Podivína Celkový pohled'></a>";
$p97="<A href='097-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m97."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p98="<A href='098-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m98."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p99="<A href='099-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m99."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína.' title='Pozdrav z Podivína.'></a>";

?>