<?php
$m34="m133.gif";
$m35="m141.gif";
$m36="m143.gif";
$m37="m142.gif";
$m38="m151.gif";
$m39="m152.gif";
$m40="m153.gif";
$m41="m161.gif";
$m42="m162.gif";
$m43="m163.gif";
$m44="m171.gif";
$m45="m172.gif";
$m46="m173.gif";
$m47="m182.gif";
$m48="m181.gif";
$m49="m191.gif";
$m50="m192.gif";
$m51="m193.gif";
$m52="m201.gif";
$m53="m202.gif";
$m54="m203.gif";
$m55="m211.gif";
$m56="m212.gif";
$m57="m213.gif";
$m58="m221.gif";
$m59="m222.gif";
$m60="m223.gif";
$m61="m231.gif";
$m62="m232.gif";
$m63="m233.gif";
$m64="m241.gif";
$m65="m242.gif";
$m66="m243.gif";

$p34="<A href='034-pohlednice-podivin-namesti.php'><img src='pm/".$m34."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p35="<A href='035-pohlednice-podivin.php'><img src='pm/".$m35."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p36="<A href='036-pohlednice-podivin-namesti.php'><img src='pm/".$m36."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Námìstí'' title='PODIVÍN - Námìstí''></a>";
$p37="<A href='037-pohlednice-kostel-podivin.php'><img src='pm/".$m37."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Kostel' - ' Podivín'' title=''Kostel' - ' Podivín''></a>";
$p38="<A href='038-pohlednice-podivin.php'><img src='pm/".$m38."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p39="<A href='039-pohlednice-podivin.php'><img src='pm/".$m39."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p40="<A href='040-pohlednice-podivin.php'><img src='pm/".$m40."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p41="<A href='041-pohlednice-podivin.php'><img src='pm/".$m41."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p42="<A href='042-pohlednice-podivin.php'><img src='pm/".$m42."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p43="<A href='043-pohlednice-podivin.php'><img src='pm/".$m43."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p44="<A href='044-pohlednice-podivin.php'><img src='pm/".$m44."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p45="<A href='045-pohlednice-podivin.php'><img src='pm/".$m45."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p46="<A href='046-pohlednice-podivin.php'><img src='pm/".$m46."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p47="<A href='047-pohlednice-pozdrav-z-podivin-gruss-aus-kostel-kostel-rybarska-ulice.php'><img src='pm/".$m47."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podivín - Gruss aus Kostel' - Kostel - Rybáøská ulice' title=''Pozdrav z Podivín - Gruss aus Kostel' - Kostel - Rybáøská ulice'></a>";
$p48="<A href='048-pohlednice-pozdrav-z-podivina-palackeho-trida-rybare.php'><img src='pm/".$m48."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podivína' Palackého tøída - Rybáøe ' title=''Pozdrav z Podivína' Palackého tøída - Rybáøe '></a>";
$p49="<A href='049-pohlednice-lednice-januv-hrad-eisgrub-hansenburg.php'><img src='pm/".$m49."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE Janùv hrad EISGRUB Hansenburg' title='LEDNICE Janùv hrad EISGRUB Hansenburg'></a>";
$p50="<A href='050-pohlednice-lednice-eisgrub-januv-hrad-die-hansenburg.php'><img src='pm/".$m50."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE - EISGRUB Janùv hrad - Die Hansenburg' title='LEDNICE - EISGRUB Janùv hrad - Die Hansenburg'></a>";
$p51="<A href='051-pohlednice-pozdrav-z-podyji-musov-podivin-valtice-mikulov-lednice.php'><img src='pm/".$m51."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podyjí' Mušov, Podivín, Valtice, Mikulov, Lednice' title=''Pozdrav z Podyjí' Mušov, Podivín, Valtice, Mikulov, Lednice'></a>";
$p52="<A href='052-pohlednice-podivin.php'><img src='pm/".$m52."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p53="<A href='053-pohlednice-podivin.php'><img src='pm/".$m53."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p54="<A href='054-pohlednice-kostel-sv-petra-a-pavla-v-podivine.php'><img src='pm/".$m54."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel sv Petra a Pavla v Podivínì' title='Kostel sv Petra a Pavla v Podivínì'></a>";
$p55="<A href='055-pohlednice-podivin-rakvice-okres-breclav.php'><img src='pm/".$m55."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - RAKVICE okres Bøeclav ' title='PODIVÍN - RAKVICE okres Bøeclav '></a>";
$p56="<A href='056-pohlednice-hotel-arcade-podivin-lezici-v-sousedstvi-lednicko-valtickeho-arealu.php'><img src='pm/".$m56."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Hotel ARCADE Podivín Ležící v sousedství Lednicko-valtického areálu ' title='Hotel ARCADE Podivín Ležící v sousedství Lednicko-valtického areálu '></a>";
$p57="<A href='057-pohlednice-elsgrub-mahren-hansenburg.php'><img src='pm/".$m57."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Elsgrub, Mähren Hansenburg ' title='Elsgrub, Mähren Hansenburg '></a>";
$p58="<A href='058-pohlednice-podivin.php'><img src='pm/".$m58."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p59="<A href='059-pohlednice-podivin.php'><img src='pm/".$m59."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p60="<A href='060-pohlednice-podivin.php'><img src='pm/".$m60."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p61="<A href='061-pohlednice-podivin.php'><img src='pm/".$m61."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p62="<A href='062-pohlednice-podivin.php'><img src='pm/".$m62."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p63="<A href='063-pohlednice-podivin.php'><img src='pm/".$m63."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p64="<A href='064-pohlednice-podivin-januv-hrad-hodova-chasa.php'><img src='pm/".$m64."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Janùv hrad - Hodová chasa ' title='PODIVÍN Janùv hrad - Hodová chasa '></a>";
$p65="<A href='065-pohlednice-podivin-januv-hrad-hrbitovni-brana-zidovska-kaple.php'><img src='pm/".$m65."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Janùv hrad - Høbitovní brána Židovská kaple ' title='PODIVÍN Janùv hrad - Høbitovní brána Židovská kaple '></a>";
$p66="<A href='066-pohlednice-januv-hrad.php'><img src='pm/".$m66."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad' title='Janùv hrad'></a>";

?>