<?php
$m100="m363.gif";
$m101="m371.gif";
$m102="m372.gif";
$m103="m373.gif";
$m104="m381.gif";
$m105="m382.gif";
$m106="m383.gif";
$m107="m391.gif";
$m108="m392.gif";
$m109="m393.gif";
$m110="m401.gif";
$m111="m402.gif";
$m112="m403.gif";
$m113="m411.gif";
$m114="m412.gif";
$m115="m413.gif";
$m116="m421.gif";
$m117="m422.gif";
$m118="m423.gif";
$m119="m431.gif";
$m120="m432.gif";
$m121="m433.gif";
$m122="m441.gif";
$m123="m442.gif";
$m124="m443.gif";
$m125="m451.gif";
$m126="m452.gif";
$m127="m453.gif";
$m128="m461.gif";
$m129="m462.gif";
$m130="m463.gif";
$m131="m471.gif";
$m132="m472.gif";
$p100="<A href='100-pohlednice-podivin-kostel.php'><img src='pm/".$m100."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Kostel.' title='PODIVÍN - Kostel.'></a>";
$p101="<A href='101-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m101."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p102="<A href='102-pohlednice-podivin-namesti.php'><img src='pm/".$m102."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Námìstí' title='PODIVÍN - Námìstí'></a>";
$p103="<A href='103-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m103."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Palackého tøída' title='Pozdrav z Podivína Palackého tøída'></a>";
$p104="<A href='104-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m104."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína.' title='Pozdrav z Podivína.'></a>";
$p105="<A href='105-pohlednice-podivinobecna-a-mestanska-skola.php'><img src='pm/".$m105."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Obecná a mìšanská škola.' title='PODIVÍN Obecná a mìšanská škola.'></a>";
$p106="<A href='106-pohlednice-pozdrav-z-podivina-mestanska-a-obecna-skola.php'><img src='pm/".$m106."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Mìšanská a obecná škola' title='Pozdrav z Podivína Mìšanská a obecná škola'></a>";
$p107="<A href='107-pohlednice-pozdrav-z-podivina-mestanska-a-obecna-skola.php'><img src='pm/".$m107."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína. Mìšanská a obecná škola.' title='Pozdrav z Podivína. Mìšanská a obecná škola.'></a>";
$p108="<A href='108-pohlednice-podivin-skoly-mestanske-a-obecne.php'><img src='pm/".$m108."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Školy mìšanské a obecné ' title='PODIVÍN - Školy mìšanské a obecné '></a>";
$p109="<A href='109-pohlednice-obecna-a-mestanska-skola-v-podivine.php'><img src='pm/".$m109."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Obecná a mìšanská škola   v Podivínì ' title='Obecná a mìšanská škola   v Podivínì '></a>";
$p110="<A href='110-pohlednice-podivin-obecna-a-mestanska-skola.php'><img src='pm/".$m110."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Obecná a mìšanská škola ' title='PODIVÍN Obecná a mìšanská škola '></a>";
$p111="<A href='111-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m111."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled ' title='Pozdrav z Podivína Celkový pohled '></a>";
$p112="<A href='112-pohlednice-podivin-celkovy-pohled.php'><img src='pm/".$m112."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Celkový pohled ' title='PODIVÍN - Celkový pohled '></a>";
$p113="<A href='113-pohlednice-hospodarska-zimni-skola-v-podivine.php'><img src='pm/".$m113."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Hospodáøská zimní škola v Podivínì ' title='Hospodáøská zimní škola v Podivínì '></a>";
$p114="<A href='114-pohlednice-podivin-zem-odb-hosp-skola.php'><img src='pm/".$m114."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Zem odb hosp škola ' title='Podivín - Zem odb hosp škola '></a>";
$p115="<A href='115-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m115."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled ' title='Pozdrav z Podivína Celkový pohled '></a>";
$p116="<A href='116-pohlednice-pozdrav-z-podivina-nova-ulice.php'><img src='pm/".$m116."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Nová ulice ' title='Pozdrav z Podivína Nová ulice '></a>";
$p117="<A href='117-pohlednice-pozdrav-z-podivina-hlavni-silnice.php'><img src='pm/".$m117."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Hlavní silnice ' title='Pozdrav z Podivína Hlavní silnice '></a>";
$p118="<A href='118-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m118."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p119="<A href='119-pohlednice-podivin-nadrazni-ulice.php'><img src='pm/".$m119."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Nádražní ulice' title='PODIVÍN - Nádražní ulice'></a>";
$p120="<A href='120-pohlednice-podivin-masarykovo-namesti.php'><img src='pm/".$m120."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN -  Masarykovo námìstí ' title='PODIVÍN -  Masarykovo námìstí '></a>";
$p121="<A href='121-pohlednice-kostel-ringplatz-podivin-namesti.php'><img src='pm/".$m121."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel - Ringplatz Podivín - Námìstí ' title='Kostel - Ringplatz Podivín - Námìstí '></a>";
$p122="<A href='122-pohlednice-podivin-namesti.php'><img src='pm/".$m122."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p123="<A href='123-pohlednice-podivin-pohled-z-veze.php'><img src='pm/".$m123."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Pohled z vìže' title='Podivín - Pohled z vìže'></a>";
$p124="<A href='124-pohlednice-podivin-tovarna.php'><img src='pm/".$m124."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Továrna' title='PODIVÍN - Továrna'></a>";
$p125="<A href='125-pohlednice-pozdrav-z-podivina-namesti.php'><img src='pm/".$m125."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Námìstí ' title='Pozdrav z Podivína Námìstí '></a>";
$p126="<A href='126-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m126."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel' title='Gruss aus Kostel'></a>";
$p127="<A href='127-pohlednice-podivin-nadrazi.php'><img src='pm/".$m127."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Nádraží.' title='PODIVÍN - Nádraží.'></a>";
$p128="<A href='128-pohlednice-podivin.php'><img src='pm/".$m128."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p129="<A href='129-pohlednice-podivin.php'><img src='pm/".$m129."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p130="<A href='130-pohlednice-podivin.php'><img src='pm/".$m130."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p131="<A href='131-pohlednice-podivin-skola-obecna-a-mestanska.php'><img src='pm/".$m131."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Škola obecná a mìšanská ' title='PODIVÍN - Škola obecná a mìšanská '></a>";
$p132="<A href='132-pohlednice-kostel-podivin.php'><img src='pm/".$m132."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel Podivín ' title='Kostel Podivín '></a>";

?>