<?php
$m1="m011.gif";
$m2="m012.gif";
$m3="m013.gif";
$m4="m022.gif";
$m5="m021.gif";
$m6="m031.gif";
$m7="m032.gif";
$m8="m033.gif";
$m9="m041.gif";
$m10="m042.gif";
$m11="m043.gif";
$m12="m051.gif";
$m13="m052.gif";
$m14="m053.gif";
$m15="m061.gif";
$m16="m062.gif";
$m17="m063.gif";
$m18="m072.gif";
$m19="m071.gif";
$m20="m082.gif";
$m21="m081.gif";
$m22="m091.gif";
$m23="m092.gif";
$m24="m093.gif";
$m25="m101.gif";
$m26="m102.gif";
$m27="m103.gif";
$m28="m112.gif";
$m29="m111.gif";
$m30="m122.gif";
$m31="m121.gif";
$m32="m131.gif";
$m33="m132.gif";
$m34="m133.gif";
$m35="m141.gif";
$m36="m143.gif";
$m37="m142.gif";
$m38="m151.gif";
$m39="m152.gif";
$m40="m153.gif";
$m41="m161.gif";
$m42="m162.gif";
$m43="m163.gif";
$m44="m171.gif";
$m45="m172.gif";
$m46="m173.gif";
$m47="m182.gif";
$m48="m181.gif";
$m49="m191.gif";
$m50="m192.gif";
$m51="m193.gif";
$m52="m201.gif";
$m53="m202.gif";
$m54="m203.gif";
$m55="m211.gif";
$m56="m212.gif";
$m57="m213.gif";
$m58="m221.gif";
$m59="m222.gif";
$m60="m223.gif";
$m61="m231.gif";
$m62="m232.gif";
$m63="m233.gif";
$m64="m241.gif";
$m65="m242.gif";
$m66="m243.gif";
$m67="m251.gif";
$m68="m252.gif";
$m69="m253.gif";
$m70="m262.gif";
$m71="m261.gif";
$m72="m271.gif";
$m73="m272.gif";
$m74="m273.gif";
$m75="m281.gif";
$m76="m282.gif";
$m77="m283.gif";
$m78="m291.gif";
$m79="m292.gif";
$m80="m293.gif";
$m81="m301.gif";
$m82="m302.gif";
$m83="m303.gif";
$m84="m311.gif";
$m85="m312.gif";
$m86="m313.gif";
$m87="m321.gif";
$m88="m322.gif";
$m89="m323.gif";
$m90="m332.gif";
$m91="m331.gif";
$m92="m341.gif";
$m93="m342.gif";
$m94="m343.gif";
$m95="m351.gif";
$m96="m353.gif";
$m97="m354.gif";
$m98="m361.gif";
$m99="m362.gif";
$m100="m363.gif";
$m101="m371.gif";
$m102="m372.gif";
$m103="m373.gif";
$m104="m381.gif";
$m105="m382.gif";
$m106="m383.gif";
$m107="m391.gif";
$m108="m392.gif";
$m109="m393.gif";
$m110="m401.gif";
$m111="m402.gif";
$m112="m403.gif";
$m113="m411.gif";
$m114="m412.gif";
$m115="m413.gif";
$m116="m421.gif";
$m117="m422.gif";
$m118="m423.gif";
$m119="m431.gif";
$m120="m432.gif";
$m121="m433.gif";
$m122="m441.gif";
$m123="m442.gif";
$m124="m443.gif";
$m125="m451.gif";
$m126="m452.gif";
$m127="m453.gif";
$m128="m461.gif";
$m129="m462.gif";
$m130="m463.gif";
$m131="m471.gif";
$m132="m472.gif";
$m133="m473.gif";
$m134="m481.gif";
$m135="m482.gif";
$m136="m483.gif";
$m137="m491.gif";
$m138="m492.gif";
$m139="m493.gif";
$m140="m501.gif";
$m141="m502.gif";
$m142="m503.gif";
$m143="m511.gif";
$m144="m511.gif";
$m145="m512.gif";
$m146="m521.gif";
$m147="m522.gif";
$m148="m523.gif";
$m149="m531.gif";
$m150="m532.gif";
$m151="m533.gif";
$m152="m542.gif";
$m153="m541.gif";
$m154="m551.gif";
$m155="m552.gif";
$m156="m553.gif";
$m157="m561.gif";
$m158="m562.gif";
$m159="m563.gif";
$m160="m571.gif";
$m161="m572.gif";
$m162="m573.gif";
$m163="m581.gif";
$m164="m582.gif";
$m165="m583.gif";
$m166="m591.gif";
$m167="m592.gif";
$m168="m593.gif";
$m169="m602.gif";
$m170="m601.gif";
$m171="m611.gif";
$m172="m612.gif";
$m173="m613.gif";
$m174="m621.gif";
$m175="m622.gif";
$m176="m623.gif";
$m177="m631.gif";
$m178="m632.gif";
$m179="m64or1.gif";
$m180="m64or7.gif";
$m181="m65or5.gif";
$m182="m65or2.gif";
$m183="m65or3.gif";
$m184="m65or4.gif";
$m185="m66or2.gif";
$m186="m66or3.gif";
$m187="m66or4.gif";
$m188="m67rep1.gif";
$m189="m67rep3.gif";
$m190="m67rep5.gif";
$m191="m67rep7.gif";
$m192="m67rep9.gif";
$m193="m67rep011.gif";
$m194="m67rep013.gif";
$m195="m67rep015.gif";
$m196="m67rep017.gif";
$m197="m67rep019.gif";
$m198="nova.gif";

$p1="<A href='001-pohlednice-podivin.php'><img src='pm/".$m1."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p2="<A href='002-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m2."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pohlednice z roku 1908' title='Pohlednice z roku 1908'></a>";
$p3="<A href='003-pohlednice-podivin-fara-s-radnici.php'><img src='pm/".$m3."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Fara s radnicí' title='PODIVÍN - Fara s radnicí'><br></a>";
$p4="<A href='004-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m4."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p5="<A href='005-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m5."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z  Podivína' title='Pozdrav z  Podivína'></a>";
$p6="<A href='006-pohlednice-podivin-hospodarska-skola.php'><img src='pm/".$m6."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. Hospodáøská  škola' title='PODIVÍN. Hospodáøská  škola'></a>";
$p7="<A href='007-pohlednice-nadrazni-trida.php'><img src='pm/".$m7."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Nádražní tøída' title='Nádražní tøída'></a>";
$p8="<A href='008-pohlednice-pozdrav-z-podivina-nadrazi-cukrovar.php'><img src='pm/".$m8."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Nádraží - Cukrovar' title='Nádraží - Cukrovar'></a>";
$p9="<A href='009-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m9."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p10="<A href='010-pohlednice-gruss-aus-kostel-hauptstrasse.php'><img src='pm/".$m10."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruß aus Kostel  -</a>";
$p11="<A href='011-pohlednice-pozdrav-z-podivina-kostelni-namesti.php'><img src='pm/".$m11."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Kostelní námìstí' title='Pozdrav z Podivína - Kostelní námìstí'></a>";
$p12="<A href='012-pohlednice-podivin-skoly-mestanske-a-obecne.php'><img src='pm/".$m12."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Školy mìšanské a obecné ' title='PODIVÍN - Školy mìšanské a obecné '></a>";
$p13="<A href='013-pohlednice-podivin-besedni-dum.php'><img src='pm/".$m13."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Besední dùm' title='Podivín - Besední dùm'></a>";
$p14="<A href='014-pohlednice-podivina-hospodarska-zimni-skola-obecna-a-mestanska-skola.php'><img src='pm/".$m14."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Hospodáøská zimní škola' title='Pozdrav z Podivína - Hospodáøská zimní škola'></a>";
$p15="<A href='015-pohlednice-podivin-janohrad-s-lesni-partii.php'><img src='pm/".$m15."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Janohrad s lesní partií' title='Podivín - Janohrad s lesní partií'></a>";
$p16="<A href='016-pohlednice-podivin-novosady.php'><img src='pm/".$m16."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Novosady' title='PODIVÍN - Novosady'></a>";
$p17="<A href='017-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m17."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p18="<A href='018-pohlednice-portal-s-prvni-polovice-13stoleti-objeveny-pri-oprave-kostela-v-podivine.php'><img src='pm/".$m18."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PORTÁL S PRVNÍ POLOVICE 13STOLETÍ OBJEVENÝ PØI OPRAVÌ KOSTELA V PODIVÍNÌ' title='PORTÁL S PRVNÍ POLOVICE 13. STOLETÍ OBJEVENÝ PØI OPRAVÌ KOSTELA V PODIVÍNÌ'></a>";
$p19="<A href='019-pohlednice-kostel-podivin.php'><img src='pm/".$m19."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='KOSTEL - PODIVÍN' title='KOSTEL - PODIVÍN'></a>";
$p20="<A href='020-pohlednice-podivin.php'><img src='pm/".$m20."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p21="<A href='021-pohlednice-podivin.php'><img src='pm/".$m21."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p22="<A href='022-pohlednice-podivin-masarykovo-nam.php'><img src='pm/".$m22."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Masarykovo nám.' title='PODIVÍN - Masarykovo nám.'></a>";
$p23="<A href='023-pohlednice-podivin.php'><img src='pm/".$m23."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p24="<A href='024-pohlednice-podivin.php'><img src='pm/".$m24."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p25="<A href='025-pohlednice-podivin-masarykovo-nam.php'><img src='pm/".$m25."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Masarykovo nám.' title='Podivín - Masarykovo nám.'></a>";
$p26="<A href='026-pohlednice-podivin.php'><img src='pm/".$m26."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p27="<A href='027-pohlednice-podivin-zem-hospodarska-skola.php'><img src='pm/".$m27."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - ZEM HOSPODÁØSKÁ ŠKOLA' title='PODIVÍN - ZEM HOSPODÁØSKÁ ŠKOLA'></a>";
$p28="<A href='028-pohlednice-podivin.php'><img src='pm/".$m28."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p29="<A href='029-pohlednice-podivin.php'><img src='pm/".$m29."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p30="<A href='030-pohlednice-podivin-kostel.php'><img src='pm/".$m30."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Kostel' title='Podivín - Kostel'></a>";
$p31="<A href='031-pohlednice-podivin.php'><img src='pm/".$m31."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p32="<A href='032-pohlednice-podivin.php'><img src='pm/".$m32."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p33="<A href='033-pohlednice-podivin-namesti.php'><img src='pm/".$m33."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p34="<A href='034-pohlednice-podivin-namesti.php'><img src='pm/".$m34."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p35="<A href='035-pohlednice-podivin.php'><img src='pm/".$m35."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p36="<A href='036-pohlednice-podivin-namesti.php'><img src='pm/".$m36."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Námìstí'' title='PODIVÍN - Námìstí''></a>";
$p37="<A href='037-pohlednice-kostel-podivin.php'><img src='pm/".$m37."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Kostel' - ' Podivín'' title=''Kostel' - ' Podivín''></a>";
$p38="<A href='038-pohlednice-podivin.php'><img src='pm/".$m38."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p39="<A href='039-pohlednice-podivin.php'><img src='pm/".$m39."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p40="<A href='040-pohlednice-podivin.php'><img src='pm/".$m40."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p41="<A href='041-pohlednice-podivin.php'><img src='pm/".$m41."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p42="<A href='042-pohlednice-podivin.php'><img src='pm/".$m42."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p43="<A href='043-pohlednice-podivin.php'><img src='pm/".$m43."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p44="<A href='044-pohlednice-podivin.php'><img src='pm/".$m44."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p45="<A href='045-pohlednice-podivin.php'><img src='pm/".$m45."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p46="<A href='046-pohlednice-podivin.php'><img src='pm/".$m46."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p47="<A href='047-pohlednice-pozdrav-z-podivin-gruss-aus-kostel-kostel-rybarska-ulice.php'><img src='pm/".$m47."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podivín - Gruss aus Kostel' - Kostel - Rybáøská ulice' title=''Pozdrav z Podivín - Gruss aus Kostel' - Kostel - Rybáøská ulice'></a>";
$p48="<A href='048-pohlednice-pozdrav-z-podivina-palackeho-trida-rybare.php'><img src='pm/".$m48."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podivína' Palackého tøída - Rybáøe ' title=''Pozdrav z Podivína' Palackého tøída - Rybáøe '></a>";
$p49="<A href='049-pohlednice-lednice-januv-hrad-eisgrub-hansenburg.php'><img src='pm/".$m49."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE Janùv hrad EISGRUB Hansenburg' title='LEDNICE Janùv hrad EISGRUB Hansenburg'></a>";
$p50="<A href='050-pohlednice-lednice-eisgrub-januv-hrad-die-hansenburg.php'><img src='pm/".$m50."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE - EISGRUB Janùv hrad - Die Hansenburg' title='LEDNICE - EISGRUB Janùv hrad - Die Hansenburg'></a>";
$p51="<A href='051-pohlednice-pozdrav-z-podyji-musov-podivin-valtice-mikulov-lednice.php'><img src='pm/".$m51."'  width='81' height='52' border='2' vspace='1' hspace='1' alt=''Pozdrav z Podyjí' Mušov, Podivín, Valtice, Mikulov, Lednice' title=''Pozdrav z Podyjí' Mušov, Podivín, Valtice, Mikulov, Lednice'></a>";
$p52="<A href='052-pohlednice-podivin.php'><img src='pm/".$m52."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p53="<A href='053-pohlednice-podivin.php'><img src='pm/".$m53."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p54="<A href='054-pohlednice-kostel-sv-petra-a-pavla-v-podivine.php'><img src='pm/".$m54."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel sv Petra a Pavla v Podivínì' title='Kostel sv Petra a Pavla v Podivínì'></a>";
$p55="<A href='055-pohlednice-podivin-rakvice-okres-breclav.php'><img src='pm/".$m55."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - RAKVICE okres Bøeclav ' title='PODIVÍN - RAKVICE okres Bøeclav '></a>";
$p56="<A href='056-pohlednice-hotel-arcade-podivin-lezici-v-sousedstvi-lednicko-valtickeho-arealu.php'><img src='pm/".$m56."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Hotel ARCADE Podivín Ležící v sousedství Lednicko-valtického areálu ' title='Hotel ARCADE Podivín Ležící v sousedství Lednicko-valtického areálu '></a>";
$p57="<A href='057-pohlednice-elsgrub-mahren-hansenburg.php'><img src='pm/".$m57."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Elsgrub, Mähren Hansenburg ' title='Elsgrub, Mähren Hansenburg '></a>";
$p58="<A href='058-pohlednice-podivin.php'><img src='pm/".$m58."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p59="<A href='059-pohlednice-podivin.php'><img src='pm/".$m59."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p60="<A href='060-pohlednice-podivin.php'><img src='pm/".$m60."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p61="<A href='061-pohlednice-podivin.php'><img src='pm/".$m61."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p62="<A href='062-pohlednice-podivin.php'><img src='pm/".$m62."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p63="<A href='063-pohlednice-podivin.php'><img src='pm/".$m63."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p64="<A href='064-pohlednice-podivin-januv-hrad-hodova-chasa.php'><img src='pm/".$m64."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Janùv hrad - Hodová chasa ' title='PODIVÍN Janùv hrad - Hodová chasa '></a>";
$p65="<A href='065-pohlednice-podivin-januv-hrad-hrbitovni-brana-zidovska-kaple.php'><img src='pm/".$m65."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Janùv hrad - Høbitovní brána Židovská kaple ' title='PODIVÍN Janùv hrad - Høbitovní brána Židovská kaple '></a>";
$p66="<A href='066-pohlednice-januv-hrad.php'><img src='pm/".$m66."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad' title='Janùv hrad'></a>";
$p67="<A href='067-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m67."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p68="<A href='068-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m68."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p69="<A href='069-pohlednice-januv-hrad-v-lednicko-valtickem-arealu.php'><img src='pm/".$m69."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad v Lednicko-valtickém areálu ' title='Janùv hrad v Lednicko-valtickém areálu '></a>";
$p70="<A href='070-pohlednice-lednice.php'><img src='pm/".$m70."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE' title='LEDNICE'></a>";
$p71="<A href='071-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m71."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p72="<A href='072-pohlednice-lednice-januv-hrad.php'><img src='pm/".$m72."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednice - Janùv hrad' title='Lednice - Janùv hrad'></a>";
$p73="<A href='073-pohlednice-lednice-breclav-a-okoli.php'><img src='pm/".$m73."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednice, Bøeclav a okolí' title='Lednice, Bøeclav a okolí'></a>";
$p74="<A href='074-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m74."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Lednicko-valtický areál' title='Lednicko-valtický areál'></a>";
$p75="<A href='075-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m75."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p76="<A href='076-pohlednice-lednicko-valticky-areal.php'><img src='pm/".$m76."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICKO-VALTICKÝ AREÁL' title='LEDNICKO-VALTICKÝ AREÁL'></a>";
$p77="<A href='077-pohlednice-zamek-lednice.php'><img src='pm/".$m77."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Zámek LEDNICE' title='Zámek LEDNICE'></a>";
$p78="<A href='078-pohlednice-zamek-lednice.php'><img src='pm/".$m78."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Zámek LEDNICE' title='Zámek LEDNICE'></a>";
$p79="<A href='079-pohlednice-lednice-valtice.php'><img src='pm/".$m79."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='LEDNICE - VALTICE' title='LEDNICE - VALTICE'></a>";
$p80="<A href='080-pohlednice-podivin-mestanska-skola.php'><img src='pm/".$m80."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Mìšanská škola' title='Podivín - Mìšanská škola'></a>";
$p81="<A href='081-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m81."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - celkový pohled' title='Pozdrav z Podivína - celkový pohled'></a>";
$p82="<A href='082-pohlednice-pozdrav-z-podivina-nova-ulice.php'><img src='pm/".$m82."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Nová ulice' title='Pozdrav z Podivína - Nová ulice'></a>";
$p83="<A href='083-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m83."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel' title='Gruss aus Kostel'></a>";
$p84="<A href='084-pohlednice-podivin-skola-a-namesti.php'><img src='pm/".$m84."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. - Škola a námìstí' title='PODIVÍN. - Škola a námìstí'></a>";
$p85="<A href='085-pohlednice-podivin-tovarna.php'><img src='pm/".$m85."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. - Továrna' title='PODIVÍN. - Továrna'></a>";
$p86="<A href='086-pohlednice-januv-hrad.php'><img src='pm/".$m86."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='JANÙV HRAD' title='JANÙV HRAD'></a>";
$p87="<A href='087-pohlednice-janohrad.php'><img src='pm/".$m87."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='JANOHRAD' title='JANOHRAD'></a>";
$p88="<A href='088-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m88."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p89="<A href='089-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m89."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p90="<A href='090-pohlednice-zamecky-areal-lednice-valtice.php'><img src='pm/".$m90."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='ZÁMECKÝ AREÁL LEDNICE - VALTICE ' title='ZÁMECKÝ AREÁL LEDNICE - VALTICE '></a>";
$p91="<A href='091-pohlednice-podivin-janodrad-most-u-janohradu.php'><img src='pm/".$m91."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - JANODRAD Most u Janohradu: ' title='PODIVÍN - JANODRAD Most u Janohradu: '></a>";
$p92="<A href='092-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m92."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p93="<A href='093-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m93."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p94="<A href='094-pohlednice-gruss-aus-kostel-garten-aussicht-bahnol-bahnstasse.php'><img src='pm/".$m94."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel Garten Aussicht, Bahnof, Bahnstrasse ' title='Gruss aus Kostel Garten Aussicht, Bahnof, Bahnstrasse '></a>";
$p95="<A href='095-pohlednice-pozdrav-z-podivina-gruss-aus-kostel.php'><img src='pm/".$m95."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Gruß aus Kostel' title='Pozdrav z Podivína Gruß aus Kostel'></a>";
$p96="<A href='096-pohlednice-pozdrav-z-podivinacelkovy-pohled.php'><img src='pm/".$m96."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled' title='Pozdrav z Podivína Celkový pohled'></a>";
$p97="<A href='097-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m97."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p98="<A href='098-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m98."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p99="<A href='099-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m99."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína.' title='Pozdrav z Podivína.'></a>";
$p100="<A href='100-pohlednice-podivin-kostel.php'><img src='pm/".$m100."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Kostel.' title='PODIVÍN - Kostel.'></a>";
$p101="<A href='101-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m101."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p102="<A href='102-pohlednice-podivin-namesti.php'><img src='pm/".$m102."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Námìstí' title='PODIVÍN - Námìstí'></a>";
$p103="<A href='103-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m103."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Palackého tøída' title='Pozdrav z Podivína Palackého tøída'></a>";
$p104="<A href='104-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m104."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína.' title='Pozdrav z Podivína.'></a>";
$p105="<A href='105-pohlednice-podivinobecna-a-mestanska-skola.php'><img src='pm/".$m105."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Obecná a mìšanská škola.' title='PODIVÍN Obecná a mìšanská škola.'></a>";
$p106="<A href='106-pohlednice-pozdrav-z-podivina-mestanska-a-obecna-skola.php'><img src='pm/".$m106."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Mìšanská a obecná škola' title='Pozdrav z Podivína Mìšanská a obecná škola'></a>";
$p107="<A href='107-pohlednice-pozdrav-z-podivina-mestanska-a-obecna-skola.php'><img src='pm/".$m107."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína. Mìšanská a obecná škola.' title='Pozdrav z Podivína. Mìšanská a obecná škola.'></a>";
$p108="<A href='108-pohlednice-podivin-skoly-mestanske-a-obecne.php'><img src='pm/".$m108."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Školy mìšanské a obecné ' title='PODIVÍN - Školy mìšanské a obecné '></a>";
$p109="<A href='109-pohlednice-obecna-a-mestanska-skola-v-podivine.php'><img src='pm/".$m109."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Obecná a mìšanská škola   v Podivínì ' title='Obecná a mìšanská škola   v Podivínì '></a>";
$p110="<A href='110-pohlednice-podivin-obecna-a-mestanska-skola.php'><img src='pm/".$m110."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN Obecná a mìšanská škola ' title='PODIVÍN Obecná a mìšanská škola '></a>";
$p111="<A href='111-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m111."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled ' title='Pozdrav z Podivína Celkový pohled '></a>";
$p112="<A href='112-pohlednice-podivin-celkovy-pohled.php'><img src='pm/".$m112."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Celkový pohled ' title='PODIVÍN - Celkový pohled '></a>";
$p113="<A href='113-pohlednice-hospodarska-zimni-skola-v-podivine.php'><img src='pm/".$m113."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Hospodáøská zimní škola v Podivínì ' title='Hospodáøská zimní škola v Podivínì '></a>";
$p114="<A href='114-pohlednice-podivin-zem-odb-hosp-skola.php'><img src='pm/".$m114."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Zem odb hosp škola ' title='Podivín - Zem odb hosp škola '></a>";
$p115="<A href='115-pohlednice-pozdrav-z-podivina-celkovy-pohled.php'><img src='pm/".$m115."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Celkový pohled ' title='Pozdrav z Podivína Celkový pohled '></a>";
$p116="<A href='116-pohlednice-pozdrav-z-podivina-nova-ulice.php'><img src='pm/".$m116."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Nová ulice ' title='Pozdrav z Podivína Nová ulice '></a>";
$p117="<A href='117-pohlednice-pozdrav-z-podivina-hlavni-silnice.php'><img src='pm/".$m117."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Hlavní silnice ' title='Pozdrav z Podivína Hlavní silnice '></a>";
$p118="<A href='118-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m118."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p119="<A href='119-pohlednice-podivin-nadrazni-ulice.php'><img src='pm/".$m119."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Nádražní ulice' title='PODIVÍN - Nádražní ulice'></a>";
$p120="<A href='120-pohlednice-podivin-masarykovo-namesti.php'><img src='pm/".$m120."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN -  Masarykovo námìstí ' title='PODIVÍN -  Masarykovo námìstí '></a>";
$p121="<A href='121-pohlednice-kostel-ringplatz-podivin-namesti.php'><img src='pm/".$m121."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel - Ringplatz Podivín - Námìstí ' title='Kostel - Ringplatz Podivín - Námìstí '></a>";
$p122="<A href='122-pohlednice-podivin-namesti.php'><img src='pm/".$m122."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p123="<A href='123-pohlednice-podivin-pohled-z-veze.php'><img src='pm/".$m123."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Pohled z vìže' title='Podivín - Pohled z vìže'></a>";
$p124="<A href='124-pohlednice-podivin-tovarna.php'><img src='pm/".$m124."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Továrna' title='PODIVÍN - Továrna'></a>";
$p125="<A href='125-pohlednice-pozdrav-z-podivina-namesti.php'><img src='pm/".$m125."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína Námìstí ' title='Pozdrav z Podivína Námìstí '></a>";
$p126="<A href='126-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m126."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel' title='Gruss aus Kostel'></a>";
$p127="<A href='127-pohlednice-podivin-nadrazi.php'><img src='pm/".$m127."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Nádraží.' title='PODIVÍN - Nádraží.'></a>";
$p128="<A href='128-pohlednice-podivin.php'><img src='pm/".$m128."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p129="<A href='129-pohlednice-podivin.php'><img src='pm/".$m129."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p130="<A href='130-pohlednice-podivin.php'><img src='pm/".$m130."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p131="<A href='131-pohlednice-podivin-skola-obecna-a-mestanska.php'><img src='pm/".$m131."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Škola obecná a mìšanská ' title='PODIVÍN - Škola obecná a mìšanská '></a>";
$p132="<A href='132-pohlednice-kostel-podivin.php'><img src='pm/".$m132."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel Podivín ' title='Kostel Podivín '></a>";
$p133="<A href='133-pohlednice-podivin.php'><img src='pm/".$m133."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p134="<A href='134-pohlednice-podivin.php'><img src='pm/".$m134."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p135="<A href='135-pohlednice-podivin.php'><img src='pm/".$m135."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p136="<A href='136-pohlednice-podivin.php'><img src='pm/".$m136."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p137="<A href='137-pohlednice-podivin.php'><img src='pm/".$m137."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p138="<A href='138-pohlednice-podivin-portal-kostela-ze-13-stoleti.php'><img src='pm/".$m138."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. Portál kostela ze 13 století ' title='PODIVÍN. Portál kostela ze 13 století '></a>";
$p139="<A href='139-pohlednice-podivin-palackeho-trida.php'><img src='pm/".$m139."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Palackého tøída' title='PODIVÍN - Palackého tøída'></a>";
$p140="<A href='140-pohlednice-podivin-zemska-hospodarska-skola.php'><img src='pm/".$m140."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - ZEMSKÁ HOSPODÁØSKÁ ŠKOLA ' title='PODIVÍN - ZEMSKÁ HOSPODÁØSKÁ ŠKOLA '></a>";
$p141="<A href='141-pohlednice-podivin-masarykovo-namesti.php'><img src='pm/".$m141."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Masarykovo námìstí' title='PODIVÍN - Masarykovo námìstí'></a>";
$p142="<A href='142-pohlednice-podivin.php'><img src='pm/".$m142."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p143="<A href='143-pohlednice-podivin-besedni-dum.php'><img src='pm/".$m143."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - BESEDNÍ DÙM ' title='PODIVÍN - BESEDNÍ DÙM '></a>";
$p144="<A href='144-pohlednice-podivin-besedni-dum.php'><img src='pm/".$m144."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - BESEDNÍ DÙM ' title='PODIVÍN - BESEDNÍ DÙM '></a>";
$p145="<A href='145-pohlednice-podivin-besedni-dum.php'><img src='pm/".$m145."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Besední dùm.' title='Podivín - Besední dùm.'></a>";
$p146="<A href='146-pohlednice-podivin.php'><img src='pm/".$m146."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p147="<A href='147-pohlednice-podivin.php'><img src='pm/".$m147."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p148="<A href='148-pohlednice-gruss-aus-kostelpodivin.php'><img src='pm/".$m148."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel Podivín' title='Gruss aus Kostel Podivín'></a>";
$p149="<A href='149-pohlednice-podivin-namesti.php'><img src='pm/".$m149."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - NÁMÌSTÍ' title='PODIVÍN - NÁMÌSTÍ'></a>";
$p150="<A href='150-pohlednice-podivin-namesti.php'><img src='pm/".$m150."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - NÁMÌSTÍ' title='PODIVÍN - NÁMÌSTÍ'></a>";
$p151="<A href='151-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m151."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus KOSTEL' title='Gruss aus KOSTEL'></a>";
$p152="<A href='152-pohlednice-cesky-mistopis-podivin.php'><img src='pm/".$m152."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='ÈESKÝ MÍSTOPIS PODIVÍN ' title='ÈESKÝ MÍSTOPIS PODIVÍN '></a>";
$p153="<A href='153-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m153."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p154="<A href='154-pohlednice-januv-hrad.php'><img src='pm/".$m154."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad' title='Janùv hrad'></a>";
$p155="<A href='155-pohlednice-podivin-janohrad.php'><img src='pm/".$m155."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Janohrad' title='PODIVÍN - Janohrad'></a>";
$p156="<A href='156-pohlednice-januv-hrad.php'><img src='pm/".$m156."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janùv hrad' title='Janùv hrad'></a>";
$p157="<A href='157-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m157."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p158="<A href='158-pohlednice-pozdrav-z-podivina-namesti-s-mestanskou-skolou.php'><img src='pm/".$m158."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z PodivínaNámìstí s mìšanskou školou ' title='Pozdrav z Podivína Námìstí s mìšanskou školou '></a>";
$p159="<A href='159-pohlednice-podivin-hospodarska-skola.php'><img src='pm/".$m159."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Hospodáøská škola' title='PODIVÍN - Hospodáøská škola'></a>";
$p160="<A href='160-pohlednice-podivin-namesti.php'><img src='pm/".$m160."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Námìstí' title='PODIVÍN - Námìstí'></a>";
$p161="<A href='161-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m161."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p162="<A href='162-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m162."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p163="<A href='163-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m163."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p164="<A href='164-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m164."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p165="<A href='165-pohlednice-podivin-namesti.php'><img src='pm/".$m165."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - námìstí' title='Podivín - námìstí'></a>";
$p166="<A href='166-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m166."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína ' title='Pozdrav z Podivína '></a>";
$p167="<A href='167-pohlednice-podivin.php'><img src='pm/".$m167."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p168="<A href='168-pohlednice-kostel-pozdrav-z-podivina.php'><img src='pm/".$m168."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel Pozdrav z Podivína ' title='Kostel Pozdrav z Podivína '></a>";
$p169="<A href='169-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m169."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p170="<A href='170-pohlednice-povoden-v-podivine-18-6-1926.php'><img src='pm/".$m170."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Povodeò v Podivínì, 18/6 1926 ' title='Povodeò v Podivínì, 18/6 1926 '></a>";
$p171="<A href='171-pohlednice-gruss-aus-kostel-pozdrav-z-podivina.php'><img src='pm/".$m171."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel Pozdrav z Podivína ' title='Gruss aus Kostel Pozdrav z Podivína '></a>";
$p172="<A href='172-pohlednice-podivin.php'><img src='pm/".$m172."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p173="<A href='173-pohlednice-podivin-namesti.php'><img src='pm/".$m173."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";
$p174="<A href='174-pohlednice-kostel-podivin.php'><img src='pm/".$m174."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Kostel - Podivín' title='Kostel - Podivín'></a>";
$p175="<A href='175-pohlednice-podivin.php'><img src='pm/".$m175."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p176="<A href='176-pohlednice-podivin.php'><img src='pm/".$m176."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p177="<A href='177-pohlednice-podivin-masarykovo-nam.php'><img src='pm/".$m177."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Masarykovo nám' title='Podivín - Masarykovo nám'></a>";
$p178="<A href='178-pohlednice-janohrad.php'><img src='pm/".$m178."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Janohrad' title='Janohrad'></a>";
$p179="<A href='179-pohlednice-originalni-fotografie.php'><img src='pm/".$m179."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie' title='Originální fotografie'></a>";
$p180="<A href='180-pohlednice-originalni-fotografie.php'><img src='pm/".$m180."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie ' title='Originální fotografie '></a>";
$p181="<A href='181-pohlednice-originalni-fotografie-kostela.php'><img src='pm/".$m181."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie kostela' title='Originální fotografie kostela'></a>";
$p182="<A href='182-pohlednice-originalni-fotografie-kostela.php'><img src='pm/".$m182."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie kostela' title='Originální fotografie kostela'></a>";
$p183="<A href='183-pohlednice-originalni-fotografie-palackeho-ul.php'><img src='pm/".$m183."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie Palackého ul' title='Originální fotografie Palackého ul'></a>";
$p184="<A href='184-pohlednice-originalni-fotografie-palackeho-ul.php'><img src='pm/".$m184."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie Palackého ul' title='Originální fotografie Palackého ul'></a>";
$p185="<A href='185-pohlednice-originalni-fotografie.php'><img src='pm/".$m185."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie' title='Originální fotografie'></a>";
$p186="<A href='186-pohlednice-originalni-fotografie.php'><img src='pm/".$m186."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie' title='Originální fotografie'></a>";
$p187="<A href='187-pohlednice-originalni-fotografie.php'><img src='pm/".$m187."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Originální fotografie' title='Originální fotografie'></a>";
$p188="<A href='188-pohlednice-repolero-titulni-strana.php'><img src='pm/".$m188."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - Titulní strana' title='Repolero - Titulní strana'></a>";
$p189="<A href='189-pohlednice-repolero-1-podivin.php'><img src='pm/".$m189."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 1 - Podivín' title='Repolero - 1 - Podivín'></a>";
$p190="<A href='190-pohlednice-repolero-2-podivin.php'><img src='pm/".$m190."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 2 - Podivín - Kostel' title='Repolero - 2 - Podivín - Kostel'></a>";
$p191="<A href='191-pohlednice-repolero-3-podivin-skola.php'><img src='pm/".$m191."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 3 - Podivín - Škola' title='Repolero - 3 - Podivín - Škola'></a>";
$p192="<A href='192-pohlednice-repolero-4-podivin-namesti.php'><img src='pm/".$m192."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 4 - Podivín - Námìstí' title='Repolero - 4 - Podivín - Námìstí'></a>";
$p193="<A href='193-pohlednice-repolero-5-podivin-dlouhan.php'><img src='pm/".$m193."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 5 - Podivín - Dlouhán' title='Repolero - 5 - Podivín - Dlouhán'></a>";
$p194="<A href='194-pohlednice-repolero-6-podivin.php'><img src='pm/".$m194."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 6 - Podivín' title='Repolero - 6 - Podivín'></a>";
$p195="<A href='195-pohlednice-repolero-7-podivin-synagoga.php'><img src='pm/".$m195."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 7 - Podivín - Synagoga' title='Repolero - 7 - Podivín - Synagoga'></a>";
$p196="<A href='196-pohlednice-repolero-8-podivin-namesti.php'><img src='pm/".$m196."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 8 - Podivín - Námìstí' title='Repolero - 8 - Podivín - Námìstí'></a>";
$p197="<A href='197-pohlednice-repolero-9-podivin-namesti.php'><img src='pm/".$m197."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Repolero - 9 - Podivín - Námìstí' title='Repolero - 9 - Podivín - Námìstí'></a>";
$p198="<A href='198-pohlednice-hledam.php'><img src='pm/".$m198."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Hledáme' title='Hledáme'></a>";

?>