<?php
$m1="m011.gif";
$m2="m012.gif";
$m3="m013.gif";
$m4="m022.gif";
$m5="m021.gif";
$m6="m031.gif";
$m7="m032.gif";
$m8="m033.gif";
$m9="m041.gif";
$m10="m042.gif";
$m11="m043.gif";
$m12="m051.gif";
$m13="m052.gif";
$m14="m053.gif";
$m15="m061.gif";
$m16="m062.gif";
$m17="m063.gif";
$m18="m072.gif";
$m19="m071.gif";
$m20="m082.gif";
$m21="m081.gif";
$m22="m091.gif";
$m23="m092.gif";
$m24="m093.gif";
$m25="m101.gif";
$m26="m102.gif";
$m27="m103.gif";
$m28="m112.gif";
$m29="m111.gif";
$m30="m122.gif";
$m31="m121.gif";
$m32="m131.gif";
$m33="m132.gif";
$p1="<A href='001-pohlednice-podivin.php'><img src='pm/".$m1."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p2="<A href='002-pohlednice-gruss-aus-kostel.php'><img src='pm/".$m2."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruss aus Kostel' title='Gruss aus Kostel'></a>";
$p3="<A href='003-pohlednice-podivin-fara-s-radnici.php'><img src='pm/".$m3."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Fara s radnicí' title='PODIVÍN - Fara s radnicí'><br></a>";
$p4="<A href='004-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m4."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p5="<A href='005-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m5."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z  Podivína' title='Pozdrav z  Podivína'></a>";
$p6="<A href='006-pohlednice-podivin-hospodarska-skola.php'><img src='pm/".$m6."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN. Hospodáøská  škola' title='PODIVÍN. Hospodáøská  škola'></a>";
$p7="<A href='007-pohlednice-nadrazni-trida.php'><img src='pm/".$m7."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Nádražní tøída' title='Nádražní tøída'></a>";
$p8="<A href='008-pohlednice-pozdrav-z-podivina-nadrazi-cukrovar.php'><img src='pm/".$m8."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Nádraží - Cukrovar' title='Nádraží - Cukrovar'></a>";
$p9="<A href='009-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m9."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p10="<A href='010-pohlednice-gruss-aus-kostel-hauptstrasse.php'><img src='pm/".$m10."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Gruß aus Kostel' title='Gruß aus Kostel'></a>";
$p11="<A href='011-pohlednice-pozdrav-z-podivina-kostelni-namesti.php'><img src='pm/".$m11."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Kostelní námìstí' title='Pozdrav z Podivína - Kostelní námìstí'></a>";
$p12="<A href='012-pohlednice-podivin-skoly-mestanske-a-obecne.php'><img src='pm/".$m12."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Školy mìšanské a obecné ' title='PODIVÍN - Školy mìšanské a obecné '></a>";
$p13="<A href='013-pohlednice-podivin-besedni-dum.php'><img src='pm/".$m13."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Besední dùm' title='Podivín - Besední dùm'></a>";
$p14="<A href='014-pohlednice-podivina-hospodarska-zimni-skola-obecna-a-mestanska-skola.php'><img src='pm/".$m14."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína - Hospodáøská zimní škola' title='Pozdrav z Podivína - Hospodáøská zimní škola'></a>";
$p15="<A href='015-pohlednice-podivin-janohrad-s-lesni-partii.php'><img src='pm/".$m15."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Janohrad s lesní partií' title='Podivín - Janohrad s lesní partií'></a>";
$p16="<A href='016-pohlednice-podivin-novosady.php'><img src='pm/".$m16."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Novosady' title='PODIVÍN - Novosady'></a>";
$p17="<A href='017-pohlednice-pozdrav-z-podivina.php'><img src='pm/".$m17."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Pozdrav z Podivína' title='Pozdrav z Podivína'></a>";
$p18="<A href='018-pohlednice-portal-s-prvni-polovice-13stoleti-objeveny-pri-oprave-kostela-v-podivine.php'><img src='pm/".$m18."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PORTÁL S PRVNÍ POLOVICE 13STOLETÍ OBJEVENÝ PØI OPRAVÌ KOSTELA V PODIVÍNÌ' title='PORTÁL S PRVNÍ POLOVICE 13. STOLETÍ OBJEVENÝ PØI OPRAVÌ KOSTELA V PODIVÍNÌ'></a>";
$p19="<A href='019-pohlednice-kostel-podivin.php'><img src='pm/".$m19."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='KOSTEL - PODIVÍN' title='KOSTEL - PODIVÍN'></a>";
$p20="<A href='020-pohlednice-podivin.php'><img src='pm/".$m20."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p21="<A href='021-pohlednice-podivin.php'><img src='pm/".$m21."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p22="<A href='022-pohlednice-podivin-masarykovo-nam.php'><img src='pm/".$m22."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - Masarykovo nám.' title='PODIVÍN - Masarykovo nám.'></a>";
$p23="<A href='023-pohlednice-podivin.php'><img src='pm/".$m23."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p24="<A href='024-pohlednice-podivin.php'><img src='pm/".$m24."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN' title='PODIVÍN'></a>";
$p25="<A href='025-pohlednice-podivin-masarykovo-nam.php'><img src='pm/".$m25."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Masarykovo nám.' title='Podivín - Masarykovo nám.'></a>";
$p26="<A href='026-pohlednice-podivin.php'><img src='pm/".$m26."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p27="<A href='027-pohlednice-podivin-zem-hospodarska-skola.php'><img src='pm/".$m27."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='PODIVÍN - ZEM HOSPODÁØSKÁ ŠKOLA' title='PODIVÍN - ZEM HOSPODÁØSKÁ ŠKOLA'></a>";
$p28="<A href='028-pohlednice-podivin.php'><img src='pm/".$m28."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p29="<A href='029-pohlednice-podivin.php'><img src='pm/".$m29."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p30="<A href='030-pohlednice-podivin-kostel.php'><img src='pm/".$m30."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Kostel' title='Podivín - Kostel'></a>";
$p31="<A href='031-pohlednice-podivin.php'><img src='pm/".$m31."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p32="<A href='032-pohlednice-podivin.php'><img src='pm/".$m32."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín' title='Podivín'></a>";
$p33="<A href='033-pohlednice-podivin-namesti.php'><img src='pm/".$m33."'  width='81' height='52' border='2' vspace='1' hspace='1' alt='Podivín - Námìstí' title='Podivín - Námìstí'></a>";

?>